"""
Tests for the MD manifest generated by regenerate_md.py.
"""
import json
from pathlib import Path

from scripts.regenerate_md import generate_md_manifest


def test_generate_md_manifest_returns_dict():
    manifest = generate_md_manifest()
    assert isinstance(manifest, dict)
    assert "generated_at" in manifest
    assert "files" in manifest
    assert "entry_counts" in manifest


def test_generate_md_manifest_includes_all_categories():
    manifest = generate_md_manifest()
    for cat in ("network-security", "system-vulnerabilities", "system-troubleshooting"):
        assert cat in manifest["entry_counts"], f"Missing category: {cat}"


def test_generate_md_manifest_files_have_required_fields():
    manifest = generate_md_manifest()
    assert len(manifest["files"]) > 0
    for f in manifest["files"]:
        assert "path" in f
        assert "size_bytes" in f
        assert "first_line" in f
        assert f["size_bytes"] > 0
        assert f["path"].endswith(".md")


def test_generate_md_manifest_includes_platform_files():
    manifest = generate_md_manifest()
    paths = [f["path"] for f in manifest["files"]]
    for expected in ("network-security/index.md", "network-security/windows.md",
                     "network-security/linux.md", "network-security/macos.md"):
        assert expected in paths, f"Missing expected file: {expected}"


def test_generate_md_manifest_total_entries_positive():
    manifest = generate_md_manifest()
    for cat, count in manifest["entry_counts"].items():
        assert count > 0, f"Category {cat} has zero entries in manifest"
